// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb-R-Jidp7WMIpgh_9Yw7G5JwdTD4EZ9E',
    appId: '1:676326647677:web:60bfe3407b2a771f7a8e14',
    messagingSenderId: '676326647677',
    projectId: 'fnl-ch',
    authDomain: 'fnl-ch.firebaseapp.com',
    storageBucket: 'fnl-ch.appspot.com',
    measurementId: 'G-FK6KH36KLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ycWXKv1dPMM7mQWSoAq7DLeVjIDvfa4',
    appId: '1:676326647677:android:26851a0716bdb7607a8e14',
    messagingSenderId: '676326647677',
    projectId: 'fnl-ch',
    storageBucket: 'fnl-ch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEd2Y9fvc4fiAvItm2AxHjLnqAG52bFZg',
    appId: '1:676326647677:ios:d4eed929abae78cb7a8e14',
    messagingSenderId: '676326647677',
    projectId: 'fnl-ch',
    storageBucket: 'fnl-ch.appspot.com',
    iosBundleId: 'com.example.finalCh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEd2Y9fvc4fiAvItm2AxHjLnqAG52bFZg',
    appId: '1:676326647677:ios:d4eed929abae78cb7a8e14',
    messagingSenderId: '676326647677',
    projectId: 'fnl-ch',
    storageBucket: 'fnl-ch.appspot.com',
    iosBundleId: 'com.example.finalCh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb-R-Jidp7WMIpgh_9Yw7G5JwdTD4EZ9E',
    appId: '1:676326647677:web:6fa01c18d963a75f7a8e14',
    messagingSenderId: '676326647677',
    projectId: 'fnl-ch',
    authDomain: 'fnl-ch.firebaseapp.com',
    storageBucket: 'fnl-ch.appspot.com',
    measurementId: 'G-Q8PQ209YVH',
  );

}